name: tblib Server Test

on:
  push:
    branches:
      - main

jobs:
  tblib-server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tblib

    - name: Start tblib server
      run: |
        nohup python -m tblib.server &
        sleep 5  # Wait for server to start

    - name: Run test script
      run: |
        python your_test_script.py  # Interact with your tblib server from a test script

    - name: Clean up
      run: |
        pkill -f tblib.server  # Clean up the server after the test
